# Games and floating apps
[[window_rule]]
match.app_id = "^(\\{}|flycast|Light.vn|Godot|xsystem35|com.libretro.RetroArch|pcsx2-qt|gamescope|steam_proton|steam_app.*|.*\\.exe)$"
match.title = ".+"
default_floating = true
default_output="DP-2"
focus_on_activate = false
default_workspace = 1

# Transparency 
[[window_rule]]
match.app_id = "^(vesktop|zenity|dev.noctalia.Noctalia|transmission-qt|org.pulseaudio.pavucontrol|spotify|lxqt-archiver|protonvpn-app|Bitwarden|pcmanfm-qt|org.nicotine_plus.Nicotine|tutanota-desktop|com.github.wwmm.easyeffects)$"
opacity = 0.95

# Specific apps
[[window_rule]]
match.app_id = "^io\\.missioncenter\\.MissionCenter$"
default_floating = true
default_size = [1020, 900]

[[window_rule]]
match.app_id = "^rmpc_search$"
default_floating = true
default_size = [500, 50]

[[window_rule]]
match.app_id = "^upscaler-overlay$"
default_output = "DP-2"
focus_on_activate = false

[[window_rule]]
match.app_id = "dev.noctalia.*$"
default_floating = true

[[window_rule]]
match.title = "Proton Launch Config"
default_floating = true
default_size = [280, 480]
opacity = 0.95

# Default workspaces
[[window_rule]]
match.app_id = "^(steam)$"
match.title = "^(Steam|Sign in to Steam)$"
default_output="DP-2"
default_workspace = 5

[[window_rule]]
match.app_id = "^(steam)"
match.title = "^(Friends List.*)$"
default_output="HDMI-A-1"
default_workspace = 2
opacity = 0.93

[[window_rule]]
match.app_id = "^(vesktop)$"
default_output="HDMI-A-1"
default_workspace = 2

[[window_rule]]
match.app_id = "^(rmpc|spotify)$"
default_output="HDMI-A-1"
default_workspace = 3

[[window_rule]]
match.app_id = "^(ff)$"
default_fullscreen = true

# Workspace rules
[[workspace]]
name = "8"
layout.mode = "scrolling"
layout.scrolling.default_width_fraction = 1.0