bind_to_address "$XDG_RUNTIME_DIR/mpd.socket"
db_file                 "~/.config/mpd/database"
music_directory         "/storage/Music"	
auto_update				"yes"

audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
}
