#!/usr/bin/perl

use IO::Socket::IP;
use POSIX;
use File::Path qw(make_path);
use IO::Select;
use Encode qw(decode_utf8 encode decode);

$playQueueDesiredLength = 10;

my $mpdHost = "localhost";
my $mpdPort = "6600";
my $mpdPasswd = "";

my $sock;
my $ipc_sock;
my $sel = IO::Select->new();

$rulesChanged = 1;
@includeRules = ();
$numMpdSongs = 0;

sub readConnectionDetails() {
    my $hostEnv = $ENV{'MPD_HOST'};
    my $portEnv = $ENV{'MPD_PORT'};
    $mpdPort = $portEnv if length($portEnv) > 2;
    if (length($hostEnv) > 2) {
        my $sep = index($hostEnv, '@');
        if ($sep > 0) {
            $mpdPasswd = substr($hostEnv, 0, $sep);
            $mpdHost = substr($hostEnv, $sep + 1);
        } else {
            $mpdHost = $hostEnv;
        }
    }
}

sub readReply() {
    local $data;
    my $socketData;
    while ($sock->connected()) {
        $sock->recv($data, 1024);
        return '' if !$data;
        $socketData .= $data;
        return $socketData if $socketData =~ m/(OK)$/ || $socketData =~ m/^(OK)/;
        return '' if $socketData =~ m/^(ACK)/;
    }
}

sub connectToMpd() {
    if ($sock) {
        $sel->remove($sock);
        eval { close $sock; };
        undef $sock;
    }
    if ($mpdHost =~ m/^\//) {
        $sock = new IO::Socket::UNIX(Peer => $mpdHost, Type => 0);
    } else {
        $sock = new IO::Socket::IP(PeerAddr => $mpdHost, PeerPort => $mpdPort, Proto => 'tcp');
    }
    if ($sock && $sock->connected()) {
        $sel->add($sock);
        if (&readReply()) {
            if ($mpdPasswd) {
                $sock->send("password ${mpdPasswd}\n");
                if (!&readReply()) {
                    print "ERROR: Invalid password\n";
                    $sel->remove($sock);
                    eval { close $sock; };
                    undef $sock;
                }
            }
        } else {
            print "ERROR: Failed to connect to MPD\n";
            $sel->remove($sock);
            close($sock);
            undef $sock;
        }
    } else {
        print "ERROR: Failed to connect to MPD\n";
    }
    return $sock;
}

sub sendCommand() {
    my $cmd = shift;
    if (!($sock && $sock->connected())) {
        $sock = &connectToMpd();
    }
    my $sockData;
    if ($sock && $sock->connected()) {
        print $sock encode('utf-8' => "${cmd}\n");
        $sockData = &readReply();
    }
    return ($sockData ne '') ? decode_utf8($sockData) : $sockData;
}

sub waitForEvent() {
    while (1) {
        if (!($sock && $sock->connected())) {
            $sock = &connectToMpd();
        }
        if ($sock && $sock->connected()) {
            print $sock encode('utf-8' => "idle player playlist\n");
            while (1) {
                my @ready = $sel->can_read();
                my $mpd_ready = 0;
                my $ipc_client = undef;
                foreach my $fh (@ready) {
                    $mpd_ready = 1 if $fh == $sock;
                    $ipc_client = $ipc_sock->accept() if $fh == $ipc_sock;
                }
                if ($ipc_client) {
                    my $msg = <$ipc_client>;
                    if (defined $msg) {
                        $msg = decode('utf-8', $msg);
                        chomp $msg;
                        if ($mpd_ready) { &readReply(); }
                        else { print $sock encode('utf-8', "noidle\n"); &readReply(); }
                        &processIpcCommand($msg);
                    }
                    close $ipc_client;
                    return 1;
                } elsif ($mpd_ready) {
                    &readReply();
                    return 1;
                }
            }
        } else {
            sleep 2;
            return 0;
        }
    }
}

sub getEntries() {
    my $command = shift;
    my $key = shift;
    my @entries = ();
    my $data = &sendCommand($command);
    if (defined($data)) {
        foreach my $line (split('\n', $data)) {
            if ($line =~ m/^($key\:)/) {
                my $sep = index($line, ':');
                push(@entries, substr($line, $sep + 2)) if $sep > 0;
            }
        }
    }
    return @entries;
}

sub baseDir() {
    my $cacheDir = $ENV{'XDG_CACHE_HOME'} || "$ENV{'HOME'}/.cache";
    return "${cacheDir}/dynamic";
}

sub lockFile() {
    return &baseDir() . "/lock";
}

sub setupIpc() {
    my $dir = &baseDir();
    make_path($dir) unless -d $dir;
    my $ipc_path = "$dir/ipc.sock";
    unlink($ipc_path);
    my $server = IO::Socket::UNIX->new(
        Type   => SOCK_STREAM,
        Local  => $ipc_path,
        Listen => 5,
    ) or die "Failed to create IPC socket: $!\n";
    return $server;
}

sub processIpcCommand {
    my $msg = shift;
    if (defined($msg) && $msg =~ /^\s*reset\s*$/i) {
        @includeRules = ();
        $rulesChanged = 1;
        return;
    }
    my @args = split("\x00", $msg);
    my $tag = lc(shift @args);
    $tag = 'Title' if $tag eq 'track';
    $tag = 'Album' if $tag eq 'album';
    $tag = 'Artist' if $tag eq 'artist';
    return if $tag !~ /^(Title|Album|Artist)$/;
    my $exact = (scalar(@args) > 0 && lc($args[0]) eq 'exact') ? (shift @args, 1) : 0;
    my $query = join(" ", @args);
    return if $query eq "";
    my $ruleMatch = $exact ? "find" : "search";
    my $newRule = "$ruleMatch $tag \"$query\"";
    my @songs = &getEntries($newRule, 'file');
    if (scalar(@songs) > 0) {
        @includeRules = ($newRule);
        $rulesChanged = 1;
    }
}

sub getSongs() {
    if (scalar(@mpdSongs) < 1 || $rulesChanged == 1) {
        $numMpdSongs = 0;
        @mpdSongs = ();
        if (scalar(@includeRules) > 0) {
            foreach my $rule (@includeRules) {
                push(@mpdSongs, &getEntries($rule, 'file'));
            }
            my %seen;
            @mpdSongs = grep { !$seen{$_}++ } @mpdSongs;
        } else {
            @mpdSongs = &getEntries("list file", "file");
        }
        $numMpdSongs = scalar(@mpdSongs);
        $rulesChanged = 0;
    }
}

@playQueueHistory = ();
$playQueueHistoryLimit = 0;
$playQueueHistoryPos = 0;

sub canAdd() {
    my $file = shift;
    my $numSongs = shift;
    my $pqLimit = ($numSongs < 5) ? int(($numSongs / 2) + 0.5)
               : int(($numSongs * 0.75) + 0.5);
    $pqLimit = 200 if $pqLimit > 200;
    if ($pqLimit != $playQueueHistoryLimit) {
        $playQueueHistoryLimit = $pqLimit;
        @playQueueHistory = ();
        return 1;
    }
    my $size = scalar(@playQueueHistory);
    $size = $playQueueHistoryLimit if $size > $playQueueHistoryLimit;
    for (my $i = 0; $i < $size; ++$i) {
        return 0 if $playQueueHistory[$i] eq $file;
    }
    return 1;
}

sub storeSong() {
    my $file = shift;
    $playQueueHistoryLimit = 5 if $playQueueHistoryLimit <= 0;
    $playQueueHistoryPos = 0 if $playQueueHistoryPos >= $playQueueHistoryLimit;
    $playQueueHistory[$playQueueHistoryPos] = $file;
    $playQueueHistoryPos++;
}

sub populatePlayQueue() {
    &readConnectionDetails();
    while (1) {
        my $socketData = &sendCommand("status");
        if (defined($socketData)) {
            my $playQueueLength = 0;
            my $playQueueCurrentTrackPos = 0;
            my $isPlaying = 0;
            foreach my $val (split('\n', $socketData)) {
                if ($val =~ m/^(song\:)/) {
                    my @vals = split(": ", $val);
                    $playQueueCurrentTrackPos = $vals[1] if scalar(@vals) == 2;
                } elsif ($val =~ m/^(state\:)/) {
                    my @vals = split(": ", $val);
                    $isPlaying = 1 if scalar(@vals) == 2 && $vals[1] =~ m/^(play)/;
                }
            }

            $socketData = &sendCommand("playlist");
            if (defined($socketData)) {
                my @lines = split('\n', $socketData);
                $playQueueLength = scalar(@lines);
                $playQueueLength-- if $playQueueLength > 0 && $lines[$playQueueLength - 1] =~ m/^(OK)/;

                my $wantCurrentPos = int($playQueueDesiredLength / 2);
                my $numToDelete = $playQueueCurrentTrackPos - ($wantCurrentPos - 1);
                if ($numToDelete > 0) {
                    &sendCommand("delete 0:" . $numToDelete);
                    $playQueueLength -= $numToDelete;
                }
                $playQueueLength = 0 if $playQueueLength < 0;

                &getSongs();
                if ($numMpdSongs > 0) {
                    my $failures = 0;
                    my $added = 0;
                    while ($playQueueLength < $playQueueDesiredLength && $numMpdSongs > 0) {
                        my $pos = int(rand($numMpdSongs));
                        my $origFile = $mpdSongs[$pos];
                        my $file = $origFile;
                        $file =~ s/\\/\\\\/g;
                        $file =~ s/\"/\\\"/g;
                        if ($failures > 100 || &canAdd($origFile, $numMpdSongs)) {
                            if (&sendCommand("add \"${file}\"") ne '') {
                                &storeSong($origFile);
                                $playQueueLength++;
                                $failures = 0;
                                $added++;
                            }
                        } else {
                            $failures++;
                        }
                    }
                    if ($isPlaying == 0 && $added == $playQueueDesiredLength) {
                        &sendCommand("play 0");
                    }
                }

                if ($numMpdSongs > 0) {
                    &waitForEvent();
                } else {
                    sleep 2;
                }
            } else {
                sleep 2;
            }
        } else {
            sleep 2;
        }
    }
}

sub readPid() {
    my $fileName = shift;
    if (-e $fileName) {
        open(my $fh, $fileName);
        my @lines = <$fh>;
        close($fh);
        return $lines[0] if scalar(@lines) > 0;
    }
    return 0;
}

sub daemonize() {
    my $fileName = shift;
    chdir '/';
    umask 0;
    open STDIN,  '/dev/null'   or die "Can't read /dev/null: $!";
    open STDOUT, '>>/dev/null' or die "Can't write to /dev/null: $!";
    open STDERR, '>>/dev/null' or die "Can't write to /dev/null: $!";
    defined(my $pid = fork) or die "Can't fork: $!";
    exit if $pid;
    POSIX::setsid() or die "Can't start a new session.";
    $SIG{INT} = $SIG{TERM} = $SIG{HUP} = sub {
        unlink(&lockFile());
        unlink(&baseDir() . "/ipc.sock");
        exit(0);
    };
    open(my $fh, ">${fileName}");
    print $fh $$;
    close $fh;
}

sub start() {
    my $pidFile = &lockFile();
    my $pid = &readPid($pidFile);
    if ($pid > 0 && kill(0, $pid)) {
        print "PROCESS $pid is running!\n";
        return;
    }
    &daemonize($pidFile);
    $ipc_sock = &setupIpc();
    $sel->add($ipc_sock);
    &populatePlayQueue();
}

sub stop() {
    my $pidFile = &lockFile();
    my $pid = &readPid($pidFile);
    if ($pid > 0) {
        system("kill", $pid);
        system("pkill", "-P", $pid);
    }
}

my $cmd = $ARGV[0] || "";
if ($cmd eq "start") {
    if (defined $ARGV[1] && $ARGV[1] =~ /^\d+$/) {
        $playQueueDesiredLength = $ARGV[1];
        $playQueueDesiredLength = 10 if $playQueueDesiredLength < 10;
        $playQueueDesiredLength = 500 if $playQueueDesiredLength > 500;
    }
    &start();
} elsif ($cmd eq "stop") {
    &stop();
}  else {
    if ($cmd ne "") {
        my $ipc_path = &baseDir() . "/ipc.sock";
        my $client = IO::Socket::UNIX->new(Type => SOCK_STREAM, Peer => $ipc_path);
        if ($client) {
            my @utf8_args = map { decode('UTF-8', $_) } @ARGV;
            print $client encode('utf-8', join("\x00", @utf8_args) . "\n");
            close $client;
            exit(0);
        } else {
            print "Is the script running? Failed to connect to IPC daemon.\n";
            exit(1);
        }
    }
    print "MPD Dynamizer script\n";
    print "Usage: $0 start [num_tracks] | stop | <track|album|artist|reset> [exact] <query>\n";
}
