###################################################
##################GLOBAL SETTINGS##################
###################################################

COMPATDIR="$HOME/.steam/steam/compatibilitytools.d"
D7VK="0"
DEFAULTOVERRIDES="winepulse.drv=d" # SEPARATED BY ;
DEFAULTPROTON="Proton-GE Latest"
GAMECONFIG="$1/proton.conf"
LOCALE="ja_JP.UTF-8"
NOFIXES="1"
PREFIX="main"
PREFIXDIR="$HOME/Games/umu"
RUNTIMEUPDATE="0"
RWDIRS="/storage:/bog" # SEPARATED BY :
WAYLAND="0"